apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  labels:
    base: rabbitmq
    k8s.eip.work/layer: basicservice
spec:
  serviceName: rabbitmq-svc
  selector:
    matchLabels:
      base: rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        base: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.8
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 15672
          name: manager
        - containerPort: 5672
          name: broker
        resources:
          requests:
            memory: 512Mi
            cpu: 250m
        livenessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: rbd
      resources:
        requests:
          storage: 2Gi

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-svc
  labels:
    base: rabbitmq
spec:
  type: ClusterIP
  ports:
    - name: cluster
      port: 15672
      targetPort: 15672
    - name: client
      port: 5672
      targetPort: 5672
  selector:
    base: rabbitmq
