#! /usr/bin/python3
# -*- coding: utf-8 -*-
"""
This script is to run a http server, and receive information for deployment

Usage:
Content-Type:application/json
{
 "bigversion":"20200902",
 "email":"monkeywade@test.com",
 "type":"test"
 "update_time":"2020-9-2 15:30:00"
}

Options:
    None

"""

import os
import time
from datetime import datetime
import flask
from flask import jsonify
from flask import request
import logging
from logging import FileHandler
from apscheduler.schedulers.background import BackgroundScheduler

server = flask.Flask(__name__)
@server.route('/bigversion', methods=['get', 'post'])

def bigversionPost():
    """
    receive "bigversion", "email", "type", "update_time" from front-end users

    :param str bigversion: bigversion is a version from release system, like "20200902"
    :param str email: no use at present, for sending emails in the future, like "monkeywade@test.com"
    :param str type: to distinguish different enviroment, just for "test" at present
    :param datetime update_time: time to run a update task, like "2020-9-2 15:30:00"
    :param bool need_write: need to write message into local file
    """
    if request.method == 'POST':
        params = request.json
        global bigversion, update_time
        try:
            bigversion = params.get('bigversion')
            email = params.get('email')
            type = params.get('type')
            update_time = params.get('update_time')

            if bigversion and email and type and update_time:
                if type == "test":
                    # write "bigversion" and "update_time" into release_info.txt
                    with open("release_info.txt", "r+") as f:
                        # if "update_time" has been in release_info.txt, then break
                        need_write = True
                        for line in f:
                            if update_time in line:
                                need_write = False
                                server.logger.warning("[WARNING] - find duplicate update_time in release_info.txt")
                                return jsonify({"code":-994, "msg": "A task has been scheduled at %s with bigversion %s, please use another time" %
                                                (update_time, bigversion)})
                                break
                        if need_write:
                            f.write(bigversion + " " + update_time + "\n")
                            server.logger.info("[INFO] - receive update massage: bigversion:%s at %s, send email to %s\n" % (bigversion, update_time, email))
                            # 调用scheduleTask函数进行任务调度
                            scheduleTask()
                            server.logger.info("[INFO] - scheduleTask successfully")
                            return jsonify({"code": 200, "msg": "message sent successfully, update will be run at %s" % (update_time)})
                else:
                    server.logger.warning("[WARNING] - type error, expect value uat")
                    return jsonify({"code": 1000, "msg": "message sent successfully but type not match"})

            else:
                if not bigversion:
                    server.logger.error("[ERROR] - bigversion not found")
                    return jsonify({"code":-995, "msg":"bigversion not found"})
                if not email:
                    server.logger.error("[ERROR] - email not found")
                    return jsonify({"code":-996, "msg":"email not found"})
                if not type:
                    server.logger.error("[ERROR] - type not found")
                    return jsonify({"code":-997, "msg":"type not found"})
                if not update_time:
                    server.logger.error("[ERROR] - update_time not found")
                    return jsonify({"code":-998, "msg":"update_time not found"})

        except Exception as e:
            raise e

    else:
        server.logger.error("[ERROR] - method error, expect POST but others")
        return jsonify({"code":-999, "msg":"method error"})

def scheduleTask():
    scheduler = BackgroundScheduler()
    scheduler.add_job(runTask, 'date', run_date=update_time)
    scheduler.start()

def runTask():
    os.popen("bash start_deploy.sh %s >> ../log/deploy.log" % (bigversion))

if __name__ == '__main__':
    server.run(debug=True, port=30009, host='0.0.0.0')
